name:                clash-compucolor2
version:             0.1.0
synopsis:            "Compucolor II home computer"
homepage:            https://github.com/gergoerdi/clash-compucolor2
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2020 Gergő Érdi
category:            Hardware

extra-source-files:
  - LICENSE
  - README.md

data-files:
  - image/*

custom-setup:
  dependencies:
    - base
    - Cabal
    - clashilator

dependencies:
  - base >= 4.7 && < 5
  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib
  - retroclash-sim
  - clash-shake
  - intel8080

  - regex-applicative
  - filtrable

  - sdl2
  - terminal

  - bytestring
  - mtl
  - transformers
  - array
  - lens
  - barbies
  - barbies-th
  - tuple
  - extra
  - template-haskell

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

library:
  source-dirs: src
  exposed-modules:
    - Hardware.Compucolor2
    - Hardware.Compucolor2.CRT5027
    - Hardware.Compucolor2.TMS5501
    - Hardware.Compucolor2.Video
    - Hardware.Compucolor2.Sim
    - Hardware.Compucolor2.Sim.Clash
    - Hardware.Compucolor2.Sim.Terminal
    - Hardware.Compucolor2.Sim.SDL
    
executables:
      
  compucolor2-verilator:
    source-dirs: sim
    main: verilator.hs
    dependencies:
      - clash-compucolor2
      - retroclash-sim
      - sdl2
      - extra
    verbatim:
      x-clashilator-top-is: Hardware.Compucolor2
