name:                clash-compucolor2
version:             0.1.0
synopsis:            "Compucolor II home computer"
homepage:            https://github.com/gergoerdi/clash-compucolor2
license:             MIT
author:              Gergő Érdi
maintainer:          gergo@erdi.hu
copyright:           2020 Gergő Érdi
category:            Hardware

extra-source-files:
  - LICENSE
  - README.md

data-files:
  - image/*

custom-setup:
  dependencies:
    - base
    - Cabal
    - clashilator

dependencies:
  - base >= 4.7 && < 5
  - clash-prelude
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib
  - clash-shake
  - intel8080

  - regex-applicative
  - filtrable

  - mtl
  - transformers
  - array
  - lens
  - barbies
  - barbies-th
  - tuple
  - extra
  - template-haskell

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators

ghc-options:
  -fexpose-all-unfoldings -fno-worker-wrapper
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

flags:
  sim:
    manual: True
    default: True
  verilator:
    manual: True
    default: False

library:
  source-dirs: src
  exposed-modules:
    - Hardware.Compucolor2
    - Hardware.Compucolor2.CRT5027
    - Hardware.Compucolor2.TMS5501
    - Hardware.Compucolor2.Video
    - Hardware.Compucolor2.Video.Plot
    - Hardware.Compucolor2.Sim
    
executables:
  compucolor2-font:
    source-dirs: sim
    main: font.hs
    other-modules: []
    dependencies:
      - clash-compucolor2
      - retroclash-sim
      - bytestring
    when:
    - condition: "!flag(sim)"
      buildable: false

  compucolor2-screen:
    source-dirs: sim
    main: screen.hs
    other-modules: []
    dependencies:
      - clash-compucolor2
      - retroclash-sim
      - bytestring
    when:
    - condition: "!flag(sim)"
      buildable: false

  compucolor2-cpu-screen:
    source-dirs: sim
    main: cpu-screen.hs
    dependencies:
      - clash-compucolor2
      - retroclash-sim
      - bytestring
      - terminal
    when:
    - condition: "!flag(sim)"
      buildable: false

  compucolor2-cpu-screen-verilator:
    source-dirs: sim
    main: cpu-screen-verilator.hs
    dependencies:
      - clash-compucolor2
      - retroclash-sim
      - bytestring
      - terminal
    verbatim:
      x-clashilator-top-is: Hardware.Compucolor2
      x-clashilator-entity: simEntity
    when:
    - condition: "!(flag(sim) && flag(verilator))"
      buildable: false

  compucolor2-cpu-textscreen:
    source-dirs: sim
    main: cpu-textscreen.hs
    dependencies:
      - clash-compucolor2
      - retroclash-sim
      - terminal
    when:
    - condition: "!flag(sim)"
      buildable: false

  compucolor2-cpu-textscreen-verilator:
    source-dirs: sim
    main: cpu-textscreen-verilator.hs
    other-modules:
      - Hardware.Compucolor2.Sim.Terminal
    dependencies:
      - clash-compucolor2
      - retroclash-sim
      - terminal
    verbatim:
      x-clashilator-top-is: Hardware.Compucolor2
      x-clashilator-entity: simEntity
    when:
    - condition: "!(flag(sim) && flag(verilator))"
      buildable: false

  compucolor2-sim:
    source-dirs: sim
    main: sim.hs
    other-modules: []
    dependencies:
      - clash-compucolor2
      - retroclash-sim
    when:
    - condition: "!flag(sim)"
      buildable: false
      
  compucolor2-verilator:
    source-dirs: sim
    main: verilator.hs
    other-modules: []
    dependencies:
      - clash-compucolor2
      - retroclash-sim
      - extra
    verbatim:
      x-clashilator-top-is: Hardware.Compucolor2
    when:
    - condition: "!(flag(sim) && flag(verilator))"
      buildable: false
